AllCops:
  NewCops: enable

Metrics/ClassLength:
  Max: 150

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
